module.exports = {
  enabled: true,
  fields: [
    // "status",
    // "dayName",
    // "dateHijri",
    "dateAD",
    "paymentMethod",
    "bankName",
    "ibanNumber",
    "bankNameFrom",
    "ibanNumberFrom",
    "bankNameTo",
    "ibanNumberTo",
    "transactionType",
    "managementName",
    "supplier",
    "item",
    "totalAmount",
    // "totalAmountText",
    "deductedFrom",
    "addedTo",
    "notes",
  ],
};
